package au.edu.anu.quirkus.ui.addpost;

import static android.view.ViewGroup.LayoutParams.WRAP_CONTENT;

import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.ColorFilter;
import android.graphics.Paint;
import android.graphics.PixelFormat;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.ShapeDrawable;
import android.graphics.drawable.shapes.OvalShape;
import android.graphics.drawable.shapes.RectShape;
import android.graphics.drawable.shapes.RoundRectShape;
import android.graphics.drawable.shapes.Shape;
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.lifecycle.ViewModelProvider;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CompoundButton;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import android.widget.Toast;

import au.edu.anu.quirkus.R;

/**
 * @author Arjun Raj
 * <p>
 * Handles the creation and working of Tag fragment and
 * Sub Tag fragment in AddPost Activity class
 * <p>
 * Autogenerated:
 * A simple {@link Fragment} subclass.
 * Use the {@link HorizontalButtonFragment#newInstance} factory method to
 * create an instance of this fragment.
 */
public class HorizontalButtonFragment extends Fragment {

    // TODO: Rename parameter arguments, choose names that match
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_PARAM1 = "param1";
    private static final String ARG_PARAM2 = "param2";
    private static final String ARG_PARAM3 = "param3";

    // TODO: Rename and change types of parameters
    private String mParam1;
    private String mParam2;
    private String mParam3;

    public HorizontalButtonFragment() {
        // Required empty public constructor

    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment HorizontalButtonFragment.
     */
    // TODO: Rename and change types and number of parameters
    public static HorizontalButtonFragment newInstance(String param1, String param2, String param3) {
        HorizontalButtonFragment fragment = new HorizontalButtonFragment();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, param1);
        args.putString(ARG_PARAM2, param2);
        args.putString(ARG_PARAM3, param3);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);
            mParam3 = getArguments().getString(ARG_PARAM3);
        }

    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_horizontal_button, container, false);
    }


    /**
     * Add Title and buttons
     *
     * @param view The View returned by {@link #onCreateView(LayoutInflater, ViewGroup, Bundle)}.
     * @param savedInstanceState If non-null, this fragment is being re-constructed
     * from a previous saved state as given here.
     */
    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        // Model
        AddPostModel addPostModel = new ViewModelProvider(requireActivity()).get(AddPostModel.class);

        // Title
        TextView title = (TextView) view.findViewById(R.id.heading_text_view);
        title.setText(mParam1);

        // Buttons
        RadioGroup radioGroup = new RadioGroup(getContext());
        radioGroup.setOrientation(LinearLayout.HORIZONTAL);
        LinearLayout layout = view.findViewById(R.id.linear_layout);
        String[] buttonNames = mParam2.split(";");
        String[] buttonColours = mParam3.split(";");

        // Styling
        int padding = 100;

        for (int i = 0; i < buttonNames.length; i++) {
            String buttonName = buttonNames[i];
            String buttonColour = buttonColours[i];

            // Styling
            RadioButton toAdd = new RadioButton(getContext());
//            toAdd.setBackgroundColor(Color.parseColor(buttonColour));

            toAdd.setText(buttonName); // Button Text
            toAdd.setButtonDrawable(null); // Remove circle
            toAdd.setPadding(40, 10, 40, 10); // Text Padding
            toAdd.setAlpha(0.6f); // Opacity

            // Set radius and colour to buttons
            Drawable backgroundDrawable = new GradientDrawable();
            ((GradientDrawable) backgroundDrawable).setColor(Color.parseColor(buttonColour));
            ((GradientDrawable) backgroundDrawable).setCornerRadius(50);

            toAdd.setBackground(backgroundDrawable);

            // Margin between buttons
            ViewGroup.MarginLayoutParams marginLayoutParams =
                    new ViewGroup.MarginLayoutParams(WRAP_CONTENT, WRAP_CONTENT);
            marginLayoutParams.setMargins(0, 0, 40, 0);
            toAdd.setLayoutParams(marginLayoutParams);

            // Listener to change appearance of button when clicked
            toAdd.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
                @Override
                public void onCheckedChanged(CompoundButton compoundButton, boolean b) {
                    // Clicked
                    if (b){
                        compoundButton.setTranslationZ(30);
//                        compoundButton.setElevation(50f);
                        compoundButton.setAlpha(1f);
                    }else {
                        compoundButton.setTranslationZ(0);
//                        compoundButton.setElevation(0);
                        compoundButton.setAlpha(0.6f);
                    }
                }
            });

            radioGroup.addView(toAdd);
        }
        layout.addView(radioGroup);
        radioGroup.setOnCheckedChangeListener(new RadioGroup.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(RadioGroup group, int checkedId) {

                // on below line we are getting radio button from our group.
                RadioButton selectedRadioButton = view.findViewById(checkedId);

                // update model
                if (mParam1.equals("Tags")){
                    addPostModel.selectCategory(selectedRadioButton);
                }
                else
                    addPostModel.selectSubCategory(selectedRadioButton);

                // on below line we are displaying a toast message.
//                Toast.makeText(getContext(), "Selected Radio Button is : " + selectedRadioButton.getText(), Toast.LENGTH_SHORT).show();
            }
        });
    }
}